description: This playbook sends email alerts to admins for Armorblox incidents that
  need review.
id: Armorblox Needs Review
inputs:
- description: The receiver's mail list.
  key: recipient_mail_address
  playbookInputQuery:
  required: false
  value:
    simple: ankita353535@gmail.com
- description: ""
  key: sender_mail_address
  playbookInputQuery:
  required: false
  value:
    simple: test.armorblox@gmail.com
- description: ""
  key: sender_mail_password
  playbookInputQuery:
  required: false
  value:
    simple: Armorb123@
- description: ""
  key: smtp_server
  playbookInputQuery:
  required: false
  value:
    simple: smtp.gmail.com
- description: ""
  key: smtp_port
  playbookInputQuery:
  required: false
  value:
    simple: "465"
name: Armorblox_NeedsReview
outputs:
- contextPath: Armorblox.Threat.remediation_actions
  type: string
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0a828c6a-22b7-4d63-8449-187f7ebb3036
      iscommand: false
      name: ""
      version: -1
    taskid: 0a828c6a-22b7-4d63-8449-187f7ebb3036
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.armorbloxincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Armorblox
      description: 'Check the recommended remediation action for any incident '
      id: a0f7d23d-bde9-4c0c-806f-7982fb19e51a
      iscommand: true
      name: check-remediation-action
      script: Armorblox|||armorblox-check-remediation-action
      type: regular
      version: -1
    taskid: a0f7d23d-bde9-4c0c-806f-7982fb19e51a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 190
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.armorbloxincidentid}
      recipient_mail_address:
        simple: ${inputs.recipient_mail_address}
      remediation_action:
        simple: ${Armorblox.Threat.remediation_actions}
      sender_mail_address:
        simple: ${inputs.sender_mail_address}
      sender_mail_password:
        simple: ${inputs.sender_mail_password}
      smtp_port:
        simple: ${inputs.smtp_port}
      smtp_server:
        simple: ${inputs.smtp_server}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: aed8b432-8b8f-4f31-8cad-cb363036a24c
      iscommand: false
      name: ArmorBloxSendEmail
      script: 206e6b95-78af-4ee0-8ef3-ff6fda5268e3
      type: regular
      version: -1
    taskid: aed8b432-8b8f-4f31-8cad-cb363036a24c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 530
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Armorblox.Threat.remediation_actions
          operator: isEqualString
          right:
            value:
              simple: NEEDS REVIEW
      label: "YES"
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "YES":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8dadca68-a477-44e8-852f-fb4155325f70
      iscommand: false
      name: IfReviewNeeded
      type: condition
      version: -1
    taskid: 8dadca68-a477-44e8-852f-fb4155325f70
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 360
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Review Not Needed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 93aaf1ae-c0fb-439f-8914-e3e6bee484de
      iscommand: false
      name: Done
      script: Print
      type: regular
      version: -1
    taskid: 93aaf1ae-c0fb-439f-8914-e3e6bee484de
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -270,
          "y": 530
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 575,
        "width": 1110,
        "x": -270,
        "y": 50
      }
    }
  }
