description: This playbook sends email alerts to admins for Armorblox incidents that
  need review.
id: Armorblox Needs Review
inputs:
- description: The receiver's mail list.
  key: recipient_mail_address
  playbookInputQuery:
  required: false
  value:
    simple: ankita353535@gmail.com
- description: ""
  key: sender_mail_address
  playbookInputQuery:
  required: false
  value:
    simple: test.armorblox@gmail.com
- description: ""
  key: sender_mail_password
  playbookInputQuery:
  required: false
  value:
    simple: Armorb123@
- description: ""
  key: smtp_server
  playbookInputQuery:
  required: false
  value:
    simple: smtp.gmail.com
- description: ""
  key: smtp_port
  playbookInputQuery:
  required: false
  value:
    simple: "465"
name: Armorblox Needs Review
outputs:
- contextPath: Armorblox.Threat.remediation_actions
  type: string
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 75f9948a-4330-4c25-86eb-2b4263af8761
      iscommand: false
      name: ""
      version: -1
    taskid: 75f9948a-4330-4c25-86eb-2b4263af8761
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.armorbloxincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Armorblox
      description: 'Check the recommended remediation action for any incident '
      id: 5f12ed4b-ee4f-449b-8824-18b7420cd8ad
      iscommand: true
      name: check-remediation-action
      script: Armorblox|||armorblox-check-remediation-action
      type: regular
      version: -1
    taskid: 5f12ed4b-ee4f-449b-8824-18b7420cd8ad
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 190
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.armorbloxincidentid}
      recipient_mail_address:
        simple: ${inputs.recipient_mail_address}
      remediation_action:
        simple: ${Armorblox.Threat.remediation_actions}
      sender_mail_address:
        simple: ${inputs.sender_mail_address}
      sender_mail_password:
        simple: '{TOMMED}+xgd3f7uym9vmpL4eVsZOO4Y+YQe+R20U8UVv34swc6Gmp8HKZ21Cysc+lTnMCxz1CFcJs0VwzNUoAeIOGNHEv+PsedHjGKSxuzhpDVXOtg='
      smtp_port:
        simple: '{TOMMED}cG7TLTNTTLAgBYJCj27efEH0h8rbN8Cxq/+d5KKTaeHePpKLBlB28tcCrDrjGz+NgQsnWBlRkUVdlOq6ec3yHXAzYeyW3JzwlA2wygK9h+c='
      smtp_server:
        simple: '{TOMMED}vB5BUHBCn2DNegv62Lcf/74VknvbB6pBKMTYCf8/SggpIetdQVpZMZ99mebPGo4pkjRap3hMIrCot9eYju6Fc7wlTw5fcUMbDTvC9y3aDVk='
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7aa73577-b448-4572-8999-67aa35810bd1
      iscommand: false
      name: ArmorBloxSendEmail
      script: ArmorBloxSendEmail
      type: regular
      version: -1
    taskid: 7aa73577-b448-4572-8999-67aa35810bd1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 530
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Armorblox.Threat.remediation_actions
          operator: isEqualString
          right:
            value:
              simple: NEEDS REVIEW
      label: "YES"
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "YES":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2efe6b7e-49f4-45b9-843e-4799ab62789f
      iscommand: false
      name: IfReviewNeeded
      type: condition
      version: -1
    taskid: 2efe6b7e-49f4-45b9-843e-4799ab62789f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 360
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Review Not Needed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 936feb4c-4726-472c-87e3-4e6bc341d1d8
      iscommand: false
      name: Done
      script: Print
      type: regular
      version: -1
    taskid: 936feb4c-4726-472c-87e3-4e6bc341d1d8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -270,
          "y": 530
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 575,
        "width": 1110,
        "x": -270,
        "y": 50
      }
    }
  }
fromversion: 6.0.0
tests:
- No tests (auto formatted)
