id: 6f8d9151-e05d-46a5-8660-015ed71d1e9f
inputs:
- description: ""
  key: email
  playbookInputQuery:
  required: false
  value:
    simple: gangulyprateek01@gmail.com
name: Armorblox_SeverityAlerts
outputs:
- contextPath: Armorblox.Threat.remediation_actions
  type: string
quiet: true
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c3429eb6-03e6-44ee-87ff-aad9b325b2ee
      iscommand: false
      name: ""
      version: -1
    taskid: c3429eb6-03e6-44ee-87ff-aad9b325b2ee
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.armorbloxincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Armorblox
      description: 'Check the recommended remediation action for any incident '
      id: a8de223a-3ef5-4840-8650-ed87d2e6f28e
      iscommand: true
      name: check-remediation-action
      script: Armorblox|||check-remediation-action
      type: regular
      version: -1
    taskid: a8de223a-3ef5-4840-8650-ed87d2e6f28e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${incident.armorbloxincidentid}
      remediation_action:
        simple: ${Armorblox.Threat.remediation_actions}
      user_email:
        simple: ${inputs.email}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a7b2a733-0006-4783-83d8-eda70fb6f3af
      iscommand: false
      name: ArmorBloxSendEmail
      script: 206e6b95-78af-4ee0-8ef3-ff6fda5268e3
      type: regular
      version: -1
    taskid: a7b2a733-0006-4783-83d8-eda70fb6f3af
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 810
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Armorblox.Threat.remediation_actions
          operator: isEqualString
          right:
            value:
              simple: NEEDS REVIEW
      label: "YES"
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "YES":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 02744b9b-9d33-4575-8d66-2b1736e204df
      iscommand: false
      name: IfReviewNeeded
      type: condition
      version: -1
    taskid: 02744b9b-9d33-4575-8d66-2b1736e204df
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 100,
          "y": 490
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Review Not Needed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: c9153a29-ee1e-48b2-8158-f27bd69d433c
      iscommand: false
      name: Done
      script: Print
      type: regular
      version: -1
    taskid: c9153a29-ee1e-48b2-8158-f27bd69d433c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -160,
          "y": 810
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 855,
        "width": 980,
        "x": -160,
        "y": 50
      }
    }
  }
